services:
  - type: web
    name: qwepic
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: qwepic-db
          property: connectionString
      - key: JWT_PASSPHRASE
        generateValue: true
      - key: JWT_SECRET_KEY
        value: config/jwt/private.pem
      - key: JWT_PUBLIC_KEY
        value: config/jwt/public.pem
      - key: CORS_ALLOW_ORIGIN
        value: "^https://.+\\.onrender\\.com$"
      - key: MESSENGER_TRANSPORT_DSN
        value: doctrine://default?auto_setup=0
      - key: MAILER_DSN
        value: null://null
      - key: TRUSTED_PROXIES
        value: "0.0.0.0/0"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MERCURE_URL
        value: https://qwepic-mercure.onrender.com/.well-known/mercure
      - key: MERCURE_PUBLIC_URL
        value: https://qwepic-mercure.onrender.com/.well-known/mercure
      - key: MERCURE_JWT_SECRET
        sync: false
      - key: API_BASE_URL
        sync: false

  - type: web
    name: qwepic-mercure
    runtime: docker
    dockerfilePath: ./mercure/Dockerfile
    plan: free
    envVars:
      - key: SERVER_NAME
        value: ':10000'
      - key: MERCURE_PUBLISHER_JWT_KEY
        sync: false
      - key: MERCURE_SUBSCRIBER_JWT_KEY
        sync: false
      - key: MERCURE_CORS_ALLOWED_ORIGINS
        sync: false
    dockerCommand: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile

databases:
  - name: qwepic-db
    databaseName: qwepic
    user: qwepic_user
    plan: free
